#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/fonts"
uri="https://github.com/Himmalerin/kiss-fonts.git"

git clone --recursive "$uri" "$1/$repo"
profiles="$1"/etc/profile.d && mkdir -p "$profiles"
echo "export KISS_PATH=$repo/kiss-fonts:\$KISS_PATH" > "$profiles"/kiss_repo-fonts.sh
