#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/himmalerin"
uri="https://github.com/Himmalerin/kiss-himmalerin.git"
git clone --recursive "$uri" "$1/$repo"

profiles="$1"/etc/profile.d && mkdir -p "$profiles"
echo "export KISS_PATH=$repo/extra:\$KISS_PATH" > "$profiles"/kiss_repo-himmalerin.sh
