#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/eudaldgr"
uri="https://github.com/eudaldgr/kiss-repo"

git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=\$KISS_PATH:%s/libs\n" "$repo" > "$1/etc/profile.d/kiss_repo-eudaldgr.sh"
