#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/eudaldgr"
uri="https://github.com/eudaldgr/kiss-repo"
git clone --recursive "$uri" "$1/$repo"

profiles="$1"/etc/profile.d && mkdir -p "$profiles"
echo "export KISS_PATH=\$KISS_PATH:$repo/libs" > "$profiles"/kiss_repo-eudaldgr.sh
