#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/cemkeylan"
uri="https://github.com/cemkeylan/kiss-repository.git"
profiles="$1"/etc/profile.d

git clone --recursive "$uri" "$1/$repo"
mkdir -p "$profiles"
echo "export KISS_PATH=$repo/personal:\$KISS_PATH" > "$profiles"/kiss_repo-cemkeylan.sh
