#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/mmatongo"
uri="https://github.com/mmatongo/kiss"
mkdir -p "$1/$repos"
git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s/staging:\$KISS_PATH\n" "$repo" > "$1/etc/profile.d/kiss_repo-mmatongo-staging.sh"
