#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/eudaldgr"
uri="https://github.com/eudaldgr/kiss-repo"
mkdir -p "$1/$repos"
git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s/testing:\$KISS_PATH\n" "$repo" > "$1/etc/profile.d/kiss_repo-eudaldgr-testing.sh"
