#!/bin/sh -e

uri="https://github.com/trbednarzyk/KISS-Java-Repo"
name="java"

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/$name"

git clone --recursive "$uri" "$1/$repo"

profiles="$1"/etc/profile.d && mkdir -p "$profiles"
echo "export KISS_PATH=$repo:\$KISS_PATH" > "$profiles"/kiss_repo-$name.sh
