#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/eudaldgr"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s/lang:\$KISS_PATH\n" "$repo" > "$1/etc/profile.d/kiss_repo-eudaldgr-lang.sh"
