#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/dilyn-kde"
uri="https://github.com/dilyn-corner/KISS-kde"

git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s/%s:\$KISS_PATH\n" "$repo" "kde" > "$1/etc/profile.d/kiss_repo-dilyn-kde.sh"
