#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/games"

profiles="$1"/etc/profile.d && mkdir -p "$profiles"
echo "export KISS_PATH=$repo/equipment:\$KISS_PATH" > "$profiles"/kiss_repo-games-equipment.sh
