#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/games"
uri="https://github.com/sdsddsd1/kiss-games"
git clone --recursive "$uri" "$1/$repo"

profiles="$1"/etc/profile.d && mkdir -p "$profiles"
echo "export KISS_PATH=$repo/games:\$KISS_PATH" > "$profiles"/kiss_repo-games.sh
