#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/repos"
uri="https://github.com/jedahan/kiss-repo-repos"

git clone "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=\$KISS_PATH:%s\n" "$repo" > "$1/etc/profile.d/kiss_repo-repos.sh"
