#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/lang"
uri="https://github.com/mmatongo/kiss-lang"
mkdir -p "$1/$repos"
git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s/%s:\$KISS_PATH\n" "$repo" "languages" > "$1/etc/profile.d/kiss_repo-lang.sh"
