#!/bin/sh -e

repo=mmatongo
subdir=android

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
profiles="$1"/etc/profile.d
mkdir -p $profiles
printf "export KISS_PATH=%s/%s/%s:\$KISS_PATH\n" "$repos" $repo $subdir > "$profiles/kiss_repo-$repo-$subdir.sh"
