#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/talyn"
uri="https://github.com/jedahan/repo-talyn"

git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s:\$KISS_PATH\n" "$repo" > "$1/etc/profile.d/kiss_repo-talyn.sh"
